// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkbsezhvffqjmbwgrzru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYnNlemh2ZmZxam1id2dyenJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NzQ3ODMsImV4cCI6MjA2MzI1MDc4M30._kFcmKWYO-XTtfaimC04G1LIesSYMzm1Id5LqhuixKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);